<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('body'); ?>

<h2>周边的极客</h2>
<div class="row">
  <div class="col-sm-6 col-md-4">
  	<?php foreach($result->near as $value) : ?>
    <div class="thumbnail">
      <a target="_blank" href="<?= $value['user']->html_url ?>">
      	<img src="<?= $value['user']->avatar_url ?>" alt="<?= htmlspecialchars($value['user']->name) ?>" />
      </a>
      <div class="caption">
        <h3><a target="_blank" href="<?= $value['user']->html_url ?>"><?= htmlspecialchars($value['user']->name) ?></a></h3>
        <p><?= $value['user']->location ?> [<?= $value['distance'] ?>]</p>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
</div>

<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/basic.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/basic') ?>