<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>

<?php if(!empty($themes)) : ?>
<div id="theme-container" class="row">
	<?php foreach($themes as $value) : ?>
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail" node-type="theme-node" theme-id="<?= $value['id'] ?>">
			<img src="<?= $value['pic'] ? $value['pic'] : $this->path('static/img/basic/empty.jpg') ?>" alt="" />
			<div class="caption">
				<h3 class="text-center"><?= $value['name'] ?></h3>
				<p class="text-center">
					<a href="javascript:void(0)" action-type="use" class="btn btn-info" role="button"><?= _('使用'); ?></a>
					<a href="javascript:void(0)" action-type="copy" class="btn btn-info" role="button" data-toggle="modal" data-target="#theme-copy-modal" ><?= _('复制'); ?></a>
					<?php if($value['user_id']) : ?>
					<a href="javascript:void(0)" action-type="edit" class="btn btn-info" role="button"><?= _('编辑'); ?></a>
					<a href="javascript:void(0)" action-type="destroy" class="btn btn-danger" role="button"><?= _('删除'); ?></a>
					<?php endif; ?>
				</p>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
</div>

<div class="modal fade" id="theme-copy-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>

<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/theme/index.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage', ['nav'=>'theme']) ?>