<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('title') ?>
Logging...
<?php $this->_blockEnd() ?>
<?php $this->_block('header') ?>
<?php $this->css('index.css') ?>
<?php $this->_blockEnd() ?>
<?php $this->_block('body_end') ?>
<script type="text/javascript">
$(function() {
	$.jsonp("http://hiblog.azurewebsites.net/server/near/update?<?= http_build_query(['access_token' => $access_token]) ?>", function() {
		location.href = '/manage/basic';
	});
});
</script>
<?php $this->_blockEnd() ?>
<?php $this->_blockLoad('_block/basic') ?>