<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>
<form id="form-manage-basic" action="<?= $this->path('aj/manage/basicsave') ?>" class="form-horizontal" method="post" onsubmit="return false">
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-name"><?= _('博客名称'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-name" name="name" placeholder="<?= _('用于展示于标题位置'); ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-desc"><?= _('博客描述'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-desc" name="desc" placeholder="<?= _('用简洁的文字描述博客'); ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-page_count"><?= _('分页设置'); ?></label>
		<div class="col-sm-5">
            <select id="input-page_count" name="page_count" class="form-control">
                <option value="10">10</option>
                <option value="20">20</option>
                <option value="50">50</option>
                <option value="100">100</option>
            </select>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-comment_duoshuo"><?= _('评论设置'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-comment_duoshuo" name="comment_duoshuo" placeholder="<?= _('请填入多说的评论名称'); ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-timezone"><?= _('时区设置'); ?></label>
		<div class="col-sm-5">
            <select class="form-control" id="input-timezone" name="timezone">
                <?php foreach(DateTimeZone::listIdentifiers() as $value) : ?>
                <option value="<?= $value ?>"><?= $value ?></option>
                <?php endforeach; ?>
            </select>
		</div>

	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-domain"><?= _('域名设置'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-domain" name="domain" placeholder="<?= _('绑定的域名，请指使用'); ?>" />
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-1 col-sm-11">
			<button type="submit" class="btn btn-default"><?= _('保存') ?></button>
		</div>
	</div>
</form>
<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/basic.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage') ?>