<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('content'); ?>
<form id="form-manage-basic" action="<?= $this->path('aj/manage/basicsave') ?>" class="form-horizontal" method="post" onsubmit="return false">
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-name"><?= _('博客名称'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-name" name="name" placeholder="<?= _('用于展示于标题位置'); ?>" value="<?= $basic['name']; ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-desc"><?= _('博客描述'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-desc" name="desc" placeholder="<?= _('用简洁的文字描述博客'); ?>" value="<?= $basic['desc']; ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label"><?= _('分页设置'); ?></label>
		<div class="col-sm-5" id="input-page_count-radioset">
			<?php foreach([10, 20, 50, 100] as $value) : ?>
            <input type="radio" id="input-page_count-<?= $value ?>" name="page_count" value="<?= $value ?>"<?php if($basic['page_count'] == $value) : ?> checked="checkekd"<?php endif; ?> /><label for="input-page_count-<?= $value ?>"><?= $value ?></label>
            <?php endforeach; ?>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-comment_duoshuo"><?= _('评论设置'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-comment_duoshuo" name="comment_duoshuo" placeholder="<?= _('请填入多说的评论名称'); ?>" value="<?= $basic['comment_duoshuo'] ?>" />
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-timezone"><?= _('时区设置'); ?></label>
		<div class="col-sm-5">
            <select class="form-control" id="input-timezone" name="timezone">
                <?php foreach(DateTimeZone::listIdentifiers() as $value) : ?>
                <option value="<?= $value ?>"<?php if($basic['timezone'] == $value) : ?> selected="selected"<?php endif; ?>><?= $value ?></option>
                <?php endforeach; ?>
            </select>
		</div>

	</div>
	
	<div class="form-group">
		<label class="col-sm-1 control-label" for="input-domain"><?= _('域名设置'); ?></label>
		<div class="col-sm-11">
			<input type="text" class="form-control" id="input-domain" name="domain" placeholder="<?= _('如果有自己的域名，请CNAME指向，并在此填入一个绑定的域名'); ?>" value="<?= $basic['domain'] ?>" />
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-1 col-sm-11">
			<button type="submit" class="btn btn-info"><?= _('保存') ?></button>
		</div>
	</div>
</form>
<?php $this->_blockEnd(); ?>
<?php $this->_block('body_end')?>
<?php $this->js('manage/basic.js'); ?>
<?php $this->_blockEnd()?>
<?php $this->_blockLoad('_block/manage', ['nav'=>'basic']) ?>