<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('title') ?>
Githublog
<?php $this->_blockEnd() ?>
<?php $this->_block('header') ?>
<?php \Comm\View::css('/static/css/manage.css') ?>
<?php $this->_blockEnd() ?>
<?php $this->_block('body') ?>
<div class="container-fluid">
	<header>
	   <div class="row inner">
		<div class="col-md-4">
			<h1>GithuBlog</h1>
			<h2><?=_('换一种方式记录点滴') ?></h2>
		</div>
		<div class="col-md-1 col-md-offset-5">
			<a href="https://github.com/flyhope" class="button"><small>GITHUB</small> <?=_('授权登录')?></a>
		</div>
		</div>
	</header>
</div>
<?php $this->_blockEnd() ?>
<?php $this->_blockLoad('_block/main') ?>