<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('title') ?>
Githublog
<?php $this->_blockEnd() ?>
<?php $this->_block('header') ?>
<?php $this->css($this->path('static/css/manage/index.css')) ?>
<?php $this->_blockEnd() ?>
<?php $this->_block('body') ?>
<div class="container-fluid">
	<header>
		<div class="row inner">
			<div class="col-md-4">
				<h1>GithuBlog</h1>
				<h2><?=_('换一种方式记录点滴') ?></h2>
			</div>
			<div class="col-md-1 col-md-offset-5">
				<a href="<?= $this->path('github/login') ?>" class="button"><small>GITHUB</small> <?=_('授权登录')?></a>
			</div>
		</div>
	</header>


	<div class="jumbotron">
		<h3>开源</h3>
		<p>通过Github实现开源</p>
		<h3>免费</h3>
		<p>使用Github作为载体，流量无限量，空间不可估量！</p>
	</div>
</div>
<?php $this->_blockEnd() ?>
<?php $this->_blockLoad('_block/basic') ?>