<?php $this; /* @var $this \Comm\View */  ?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php $this->_blockConfig('title', 'Githublog') ?></title>
    <?php $this->cssLib('bootstrap')?>
    <?php $this->css($this->path('static/lib/jquery-ui-bootstrap/jquery-ui-1.10.0.custom.css'), false, false, true) ?>
    <?php $this->css('core/basic.css') ?>
    <!--[if lt IE 9]>
      <?php $this->jsLib('html5shiv')?>
      <?php $this->jsLib('respond_js')?>
    <![endif]-->
    <?php $this->_blockConfig('header'); ?>
  </head>
<body>
    <?php $this->_blockConfig('body'); ?>

    <?php $this->jsLib('jquery')?>
    <?php $this->jsLib('bootstrap_js')?>
    <?php $this->jsLib('jquery_ui')?>
    <?php $this->js('core/basic.js')?>
    <?php $this->_blockConfig('body_end')?>
  </body>
</html>