<?php $this; /* @var $this \Comm\View */  ?>
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php $this->_blockConfig('title') ?></title>
    <?php \Comm\View::cssLib('bootstrap') ?>
    <!--[if lt IE 9]>
      <?php \Comm\View::jsLib('html5shiv') ?>
      <?php \Comm\View::jsLib('respond_js') ?>
    <![endif]-->
    <?php $this->_blockConfig('header'); ?>
  </head>
  <body>
    <?php $this->_blockConfig('body'); ?>

    <?php \Comm\View::jsLib('jquery') ?>
    <?php \Comm\View::jsLib('bootstrap_js') ?>
    <?php $this->_blockConfig('body_end') ?>
  </body>
</html>