<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('body') ?>

<header class="container-fluid">
	<div class="container">
		<nav class="navbar navbar-inverse">
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li role="presentation"<?php if($nav ==='basic') : ?> class="active"<?php endif; ?>><a href="<?= $this->path('manage/basic') ?>"><?= _('基本设置') ?></a></li>
					<li role="presentation"<?php if($nav ==='category') : ?> class="active"<?php endif; ?>><a href="<?= $this->path('manage/category') ?>"><?= _('分类管理') ?></a></li>
					<li role="presentation"<?php if($nav ==='article') : ?> class="active"<?php endif; ?>><a href="<?= $this->path('manage/article/index') ?>"><?= _('文章管理') ?></a></li>
				</ul>

		<ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">我 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a target="_blank" href="#"><?= _('我的博客') ?></a></li>
            <li><a target="_blank" href="#"><?= _('评论管理') ?></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><?= _('退出') ?></a></li>
          </ul>
        </li>
      </ul>
			</div>
		</nav>
	</div>
</header>

<div class="container"><?php $this->_blockConfig('content') ?></div>
<?php $this->_blockEnd(); ?>
<?php $this->_blockLoad('_block/basic') ?>