<?php $this; /* @var $this \Comm\View */  ?>
<?php $this->_block('body') ?>

<header class="container-fluid">
	<div class="container">
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<li role="presentation" class="active"><a href="<?= $this->path('manage/basic') ?>"><?= _('基本设置') ?></a></li>
					<li role="presentation"><a href="<?= $this->path('manage/category') ?>"><?= _('分类管理') ?></a></li>
					<li role="presentation"><a href="<?= $this->path('manage/article') ?>"><?= _('文章管理') ?></a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li role="presentation"><a href="#">用户昵称</a></li>
					<li role="presentation"><a href="#"><?= _('退出') ?></a></li>
				</ul>
			</div>
		</nav>
	</div>
</header>

<div class="container"><?php $this->_blockConfig('content') ?></div>
<?php $this->_blockEnd(); ?>
<?php $this->_blockLoad('_block/basic') ?>